"""added next token column to store pagination token

Revision ID: bf87436890cd
Revises: 
Create Date: 2025-09-15 15:37:56.100896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf87436890cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['id'])
    op.add_column('bookmarks', sa.Column('next_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'bookmarks', ['next_token'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'user_tokens', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_tokens', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'bookmarks', type_='unique')
    op.drop_column('bookmarks', 'next_token')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
