"""Add last_front_sync_time to users table

Revision ID: c74a455f404c
Revises: e7edf8e9a7b3
Create Date: 2026-02-26 14:50:00.730808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74a455f404c'
down_revision: Union[str, Sequence[str], None] = 'e7edf8e9a7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['id'])
    op.add_column('bookmarks', sa.Column('front_sync_anchor', sa.DateTime(), nullable=True))
    op.add_column('bookmarks', sa.Column('front_sync_token', sa.String(), nullable=True))
    op.add_column('bookmarks', sa.Column('next_token', sa.String(), nullable=False))
    op.add_column('bookmarks', sa.Column('is_backfill_complete', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'medias', ['id'])
    op.create_unique_constraint(None, 'metadata', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'user_tokens', ['id'])
    op.add_column('users', sa.Column('last_front_sync_time', sa.DateTime(), nullable=True))
    op.create_index('ix_users_last_front_sync_time', 'users', ['last_front_sync_time'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_tokens', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'metadata', type_='unique')
    op.drop_constraint(None, 'medias', type_='unique')
    op.drop_column('bookmarks', 'is_backfill_complete')
    op.drop_column('bookmarks', 'next_token')
    op.drop_column('bookmarks', 'front_sync_token')
    op.drop_column('bookmarks', 'front_sync_anchor')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
