"""is_backfill_complete column

Revision ID: 4b9649897d8c
Revises: b18c2a91ef99
Create Date: 2026-04-14 12:14:26.418801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9649897d8c'
down_revision: Union[str, Sequence[str], None] = 'b18c2a91ef99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('\n    Junction table connecting bookmarks to folders.\n\n    This table establishes a many-to-many relationship between bookmarks\n    and folders. A bookmark can belong to multiple folders, and a folder\n    can contain multiple bookmarks.\n\n    Primary Keys:\n    - bookmark_id: References bookmarks.id\n    - folder_id: References folders.id\n\n    Delete Behavior: CASCADE - deleting a bookmark or folder removes the association.\n    ',
    sa.Column('bookmark_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'folder_id')
    )
    op.create_table('\n    Junction table connecting bookmarks to tags.\n\n    This table establishes a many-to-many relationship between bookmarks\n    and tags. A bookmark can have multiple tags, and a tag can be applied\n    to multiple bookmarks.\n\n    Primary Keys:\n    - bookmark_id: References bookmarks.id\n    - tag_id: References tags.id\n\n    Delete Behavior: CASCADE - deleting a bookmark or tag removes the association.\n    ',
    sa.Column('bookmark_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'tag_id')
    )
    op.drop_table('bookmark_tags')
    op.drop_table('bookmark_folders')
    op.add_column('users', sa.Column('is_backfill_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_backfill_complete')
    op.create_table('bookmark_folders',
    sa.Column('bookmark_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], name=op.f('bookmark_folders_bookmark_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('bookmark_folders_folder_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'folder_id', name=op.f('bookmark_folders_pkey'))
    )
    op.create_table('bookmark_tags',
    sa.Column('bookmark_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmarks.id'], name=op.f('bookmark_tags_bookmark_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('bookmark_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id', 'tag_id', name=op.f('bookmark_tags_pkey'))
    )
    op.drop_table('\n    Junction table connecting bookmarks to tags.\n\n    This table establishes a many-to-many relationship between bookmarks\n    and tags. A bookmark can have multiple tags, and a tag can be applied\n    to multiple bookmarks.\n\n    Primary Keys:\n    - bookmark_id: References bookmarks.id\n    - tag_id: References tags.id\n\n    Delete Behavior: CASCADE - deleting a bookmark or tag removes the association.\n    ')
    op.drop_table('\n    Junction table connecting bookmarks to folders.\n\n    This table establishes a many-to-many relationship between bookmarks\n    and folders. A bookmark can belong to multiple folders, and a folder\n    can contain multiple bookmarks.\n\n    Primary Keys:\n    - bookmark_id: References bookmarks.id\n    - folder_id: References folders.id\n\n    Delete Behavior: CASCADE - deleting a bookmark or folder removes the association.\n    ')
    # ### end Alembic commands ###
