"""Add user info fields to users table

Revision ID: 748419a1e4ab
Revises: a19ae2bdd988
Create Date: 2026-04-10 05:19:17.502946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748419a1e4ab'
down_revision: Union[str, Sequence[str], None] = 'a19ae2bdd988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tweet_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_user_info_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_user_info_update')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    op.drop_column('users', 'tweet_count')
    op.drop_column('users', 'url')
    op.drop_column('users', 'location')
    op.drop_column('users', 'verified')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
