"""Add default value for next_token column

Revision ID: a19ae2bdd988
Revises: c74a455f404c
Create Date: 2026-03-02 05:30:42.223258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19ae2bdd988'
down_revision: Union[str, Sequence[str], None] = 'c74a455f404c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add default value for next_token column in bookmarks table
    op.alter_column('bookmarks', 'next_token', 
                   existing_type=sa.VARCHAR(), 
                   nullable=False, 
                   server_default='')
    
    op.drop_index(op.f('ix_users_last_front_sync_time'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_last_front_sync_time'), 'users', ['last_front_sync_time'], unique=False)
    # ### end Alembic commands ###
