"""add_tweet_type_and_referenced_tweet_id

Revision ID: a348b1865f9e
Revises: 3d9db9dc9992
Create Date: 2026-04-22 09:32:24.931433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a348b1865f9e'
down_revision: Union[str, Sequence[str], None] = '3d9db9dc9992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_audit_logs', ['id'])
    op.add_column('bookmarks', sa.Column('referenced_tweet_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'error_logs', ['id'])
    op.add_column('posts', sa.Column('tweet_type', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'sync_jobs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_jobs', type_='unique')
    op.drop_column('posts', 'tweet_type')
    op.drop_constraint(None, 'error_logs', type_='unique')
    op.drop_column('bookmarks', 'referenced_tweet_id')
    op.drop_constraint(None, 'admin_audit_logs', type_='unique')
    # ### end Alembic commands ###
