"""Add is_read column to bookmarks

Revision ID: b18c2a91ef99
Revises: d4d56841fe83
Create Date: 2026-04-13 11:08:51.880720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18c2a91ef99'
down_revision: Union[str, Sequence[str], None] = 'd4d56841fe83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('bookmarks', 'is_read')
    # ### end Alembic commands ###
