"""drop erroneous unique constraints on medias table: drop constraint medias_media_type_key, medias_url_key, medias_preview_image_url_key, medias_alt_text_key from medias

Revision ID: d96bc9b69c92
Revises: a348b1865f9e
Create Date: 2026-04-27 09:39:51.434462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96bc9b69c92'
down_revision: Union[str, Sequence[str], None] = 'a348b1865f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medias_alt_text_key'), 'medias', type_='unique')
    op.drop_constraint(op.f('medias_media_type_key'), 'medias', type_='unique')
    op.drop_constraint(op.f('medias_preview_image_url_key'), 'medias', type_='unique')
    op.drop_constraint(op.f('medias_url_key'), 'medias', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('medias_url_key'), 'medias', ['url'])
    op.create_unique_constraint(op.f('medias_preview_image_url_key'), 'medias', ['preview_image_url'])
    op.create_unique_constraint(op.f('medias_media_type_key'), 'medias', ['media_type'])
    op.create_unique_constraint(op.f('medias_alt_text_key'), 'medias', ['alt_text'])
    # ### end Alembic commands ###
