"""author_id on post table is nullable

Revision ID: e7e83cf00f6a
Revises: ef709bb5f5ee
Create Date: 2026-04-18 01:02:42.402342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e83cf00f6a'
down_revision: Union[str, Sequence[str], None] = 'ef709bb5f5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
