"""added media tables for handling medias

Revision ID: e7edf8e9a7b3
Revises: bf87436890cd
Create Date: 2025-09-29 19:02:07.293584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7edf8e9a7b3'
down_revision: Union[str, Sequence[str], None] = 'bf87436890cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('media_key', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('preview_image_url', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alt_text'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('media_key'),
    sa.UniqueConstraint('media_type'),
    sa.UniqueConstraint('preview_image_url'),
    sa.UniqueConstraint('url')
    )
    op.add_column('posts', sa.Column('conversation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'conversation_id')
    op.drop_table('medias')
    # ### end Alembic commands ###
