"""add_front_watermark_id_and_cleanup

Revision ID: ef709bb5f5ee
Revises: b85ecd257649
Create Date: 2026-04-16 22:28:18.988375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef709bb5f5ee'
down_revision: Union[str, Sequence[str], None] = 'b85ecd257649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['id'])
    op.drop_column('bookmarks', 'is_backfill_complete')
    op.drop_column('bookmarks', 'front_sync_token')
    op.drop_column('bookmarks', 'front_sync_anchor')
    op.create_unique_constraint(None, 'medias', ['id'])
    op.create_unique_constraint(None, 'metadata', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_unique_constraint(None, 'user_tokens', ['id'])
    op.add_column('users', sa.Column('front_watermark_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'front_watermark_id')
    op.drop_constraint(None, 'user_tokens', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'metadata', type_='unique')
    op.drop_constraint(None, 'medias', type_='unique')
    op.add_column('bookmarks', sa.Column('front_sync_anchor', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookmarks', sa.Column('front_sync_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookmarks', sa.Column('is_backfill_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
